# Generated by Django 4.1.7 on 2023-02-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_transactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='transactions',
            name='is_loan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
