# Generated by Django 4.1.7 on 2023-02-21 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_transactions_options_transactions_is_loan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='is_loan',
        ),
        migrations.AddField(
            model_name='transactions',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]