# Generated by Django 4.1.7 on 2023-02-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '007'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
