# Generated by Django 4.1.7 on 2023-02-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_transactions_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='message',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='pay_request',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='status',
        ),
    ]
