# Generated by Django 4.1.7 on 2023-02-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_transactions_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='added_by',
        ),
    ]
