# Generated by Django 4.1.7 on 2023-02-26 07:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_transactions_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.transactions')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True))
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
