# Generated by Django 4.1.7 on 2023-03-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_payrequest_transactions_requests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrequest',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='payrequest',
            name='message',
            field=models.CharField(blank=True, default='Paid', max_length=50, null=True),
        ),
    ]
