# Generated by Django 4.1.7 on 2023-02-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='pay_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transactions",
            name="amount_paid",
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0, blank=True)
        ),
        migrations.AddField(
            model_name='transactions',
            name='message',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
